language: go
sudo: required
install: true
go:
  - 1.7.5
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.5

install:
  - go get -u github.com/golang/glog
  - go get -u github.com/coreos/etcd
  - go get -u github.com/Shopify/sarama
  - go get -u github.com/wvanbergen/kafka
  - go get -u github.com/tsuna/gohbase
  - go get -u github.com/garyburd/redigo
  - go get -u github.com/BurntSushi/toml
  - go get -u gopkg.in/olivere/elastic.v5
  - go get -u gopkg.in/mgo.v2