
ver = "1.0.0"
logPath = "/tmp/msg.log"

[kafkaProducer]
topic = "test"
[kafka.producer]
sync = false
brokers = ["127.0.0.1:9092"]
    [kafka.producer.zookeeper]
    root = "/kafka"
    addrs = ["127.0.0.1:2181"]
    timeout = 2000

[kafkaConsumer]
group = "archive-videoshot"
topics = ["reply_v2"]
offset = false
    [kafka.zookeeper]
    root = "/kafka"
    addrs = ["172.16.0.148:2181"]
    timeout = "200ms"
