
ver = "1.0.0"
logPath = "/tmp/msg.log"

[kafkaProducer]
topic = "test"
[kafkaProducer.producer]
sync = false
brokers = ["127.0.0.1:9092"]
    [kafkaProducer.producer.zookeeper]
    root = "/kafka"
    addrs = ["127.0.0.1:2181"]
    timeout = 2000

[kafkaConsumer]
group = "test_group"
topics = ["test"]
offset = false
    [kafkaConsumer.zookeeper]
    root = "/brokers"
    addrs = ["127.0.0.1:2181"]
    timeout = 200000
