# auth conf

ver = "1.0.0"
logPath = "/tmp/auth.log"

[auth]
encryption = "md5"
salt = "!0h#?123(ABM"

[rpcServer]
proto = "tcp"
addr = "127.0.0.1:30000"

[etcd]
name = "auth_0001"
root = "/server/auth/"
addrs = ["127.0.0.1:2379"]
timeout = "1s"

[redis]
name = "auth"
proto = "tcp"
addr = "127.0.0.1:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "24h"

