# logic conf

ver = "1.0.0"
logPath = "/tmp/logic.log"

[server]
proto = "tcp"
addr = "127.0.0.1:12000"

[rpcServer]
proto = "tcp"
addr = "127.0.0.1:22000"

[rpcClient]
    [rpcClient.authClient]
    addr = "127.0.0.1:30000"
    [rpcClient.registerClient]
    addr = "127.0.0.1:30000"

[etcd]
name = "logic_0001"
root = "/server/logic/"
addrs = ["localhost:2379"]
timeout = "1s"

[kafkaProducer]
topic = "logic_producer"
[kafkaProducer.producer]
sync = false
brokers = ["127.0.0.1:9092"]
    [kafkaProducer.producer.zookeeper]
    root = "/kafka"
    addrs = ["127.0.0.1:2181"]
    timeout = "2s"

[mongoDB]
addrs = "127.0.0.1:27017"
db = "im"
dialTimeout = "1s"
offlineMsgCollection = "offline_msg"
