# This is a TOML document. Boom.

version = "2.4.0"
user = "nobody"
pid = "/tmp/history.pid"
dir = "./"
perf = "0.0.0.0:6000"
checkFile = "/data/www/history.html"
log = "/data/log/history/"
trace = true
debug = false

[identify]
    [identify.app]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    [identify.memcache]
    name = "go-common/identify"
    proto = "tcp"
    addr = "172.16.0.148:11211"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.authHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.secretHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000

[multiHTTP]
    [multiHTTP.outer]
    addrs = ["0.0.0.0:6001"]
    maxListen = 10
    [multiHTTP.inner]
    addrs = ["0.0.0.0:6002"]
    maxListen = 10
    [multiHTTP.local]
    addrs = ["0.0.0.0:6003"]
    maxListen = 10

[redis]
name = "history"
proto = "tcp"
addr = "172.16.0.148:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "10s"

[kafka]
topic = "history"
firstTopic = "his_first"
[kafka.producer]
sync = false
brokers = ["172.16.0.148:9092"]
    [kafka.producer.zookeeper]
    root = "/kafka"
    addrs = ["172.16.0.148:2181"]
    timeout = "200ms"

[tracer]
proto = "udp"
addr = "172.16.0.148:5640"
tag = "platform/history"

[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "200ms"
readsTimeout = "1s"
writeTimeout = "200ms"
writesTimeout = "200ms"
    [hbase.zookeeper]
    root = ""
    addrs = ["172.16.33.45:2181"]
    timeout = "200ms"
