# auth conf

ver = "1.0.0"
logPath = "/tmp/router.log"

[rpcServer]
proto = "tcp"
addr = "127.0.0.1:24000"

[etcd]
name = "auth_0001"
root = "/server/router/"
addrs = ["127.0.0.1:2379"]
timeout = "1s"

[redis]
name = "router"
proto = "tcp"
addr = "127.0.0.1:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "5s"

