
ver = "1.0.0"
logPath = "/tmp/msg-job.log"

[rpcClient]
    [rpcClient.accessServerClient]
    addr = "127.0.0.1:20000"


[kafkaConsumer]
group = "msg-job"
topics = ["logic_producer"]
offset = false
    [kafkaConsumer.zookeeper]
    root = "/brokers"
    addrs = ["127.0.0.1:2181"]
    timeout = "5s"

[etcd]
name = "msg-job"
root = "/server/msg_job/"
addrs = ["localhost:2379"]
timeout = "1s"