
ver = "1.0.0"
logPath = "/tmp/msg-job.log"

[kafkaConsumer]
group = "msg-job"
topics = ["msg_server_producer"]
offset = true
    [kafkaConsumer.zookeeper]
    root = "/brokers"
    addrs = ["127.0.0.1:2181"]
    timeout = "1s"


[etcd]
name = "msg-job"
root = "/server/msg-job/"
addrs = ["localhost:2379"]
timeout = "1s"