# This is a TOML document. Boom.

version = "2.4.0"
user = "nobody"
pid = "/tmp/history.pid"
dir = "./"
perf = "0.0.0.0:6000"
checkFile = "/data/www/history.html"
log = "/data/log/history/"
trace = true
debug = false

[multiHTTP]
    [multiHTTP.outer]
    addrs = ["0.0.0.0:6001"]
    maxListen = 10
    [multiHTTP.inner]
    addrs = ["0.0.0.0:6002"]
    maxListen = 10
    [multiHTTP.local]
    addrs = ["0.0.0.0:6003"]
    maxListen = 10


[rpcClient]
    [rpcClient.registerClient]
    addr = "127.0.0.1:23000"

[redis]
name = "history"
proto = "tcp"
addr = "172.16.0.148:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "10s"
