# msg_server conf

ver = "1.0.0"
logPath = "/tmp/gateway.log"

[server]
proto = "tcp"
addr = "127.0.0.1:12000"

[rpcServer]
proto = "tcp"
addr = "127.0.0.1:22000"

[etcd]
name = "msg_server_0001"
root = "foo"
addrs = ["localhost:2379"]
timeout = 1000

[zookeeper]
root = "/server/msg_server/"
addrs = ["127.0.0.1:2181"]
timeout = 1000