# gateway conf

ver = "1.0.0"
logPath = "/tmp/gateway.log"

[server]
proto = "tcp"
addr = "0.0.0.0:18000"

[zookeeper]
root = "/microservice/account-service/"
addrs = ["127.0.0.1:2181"]
timeout = "1s"